version: '3'
services:
  postgres:
    image: 'postgres:${POSTGRES_VERSION}'
    container_name: postgres
    build: 
      context: ./database/.
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    networks:
      - my_net
    env_file: .env
    ports:
      - ${PORT_DB}:${PORT_DB}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PORT_DB=${PORT_DB}
      - POSTGRES_VERSION=${POSTGRES_VERSION}
    volumes:
      - pg_data:/var/lib/postgresql/data/
  app:
    image: goldenmanbel/docker-basics:app
    container_name: app
    build:
      context: .
      args: 
        - NODE_ENV=${NODE_ENV}
        - PORT=${PORT}
        - NODE_VERSION=${NODE_VERSION}
    networks:
      - my_net 
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - NODE_VERSION=${NODE_VERSION}
    volumes:
      - logs:/usr/src/app/logs
      # - ./logs:/usr/src/app/logs/*
      - ./:/usr/src/app 
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s 
    depends_on:
      - postgres
volumes:
  pg_data:
  logs:
networks:
  my_net:
    driver: bridge
